<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Checklist;
use App\Models\ChecklistItem;
use Illuminate\Support\Facades\DB;

class DynamicChecklistSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear old data from these tables to prevent duplicates when re-seeding
        DB::table('checklist_items')->delete();
        DB::table('checklists')->delete();

        // Create a template checklist that can be dynamically populated
        $templateChecklist = Checklist::create([
            'slug' => 'dynamic-audit-checklist',
            'title' => 'Dynamic Audit Checklist Template',
            'description' => 'Template checklist for internal audits - questions will be dynamically generated by users',
            'is_template' => true,
        ]);

        // Create a sample structure with placeholder items
        $sampleSections = [
            'General Compliance',
            'Documentation Review',
            'Process Evaluation',
            'Quality Assurance',
            'Risk Assessment'
        ];

        $order = 1;
        foreach ($sampleSections as $section) {
            ChecklistItem::create([
                'checklist_id' => $templateChecklist->id,
                'section' => $section,
                'question_text' => 'Sample question for ' . $section . ' - replace with user-generated questions',
                'display_order' => $order++,
                'is_placeholder' => true,
            ]);
        }
    }
}
